Delete From params Where ENTIDAD = 'VENTAS_HUNTER';

#  ----- Importar Distribuidores
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_SHELL1','Importar_Distribuidores.sh','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_PYTHON1','/var/opt/tel_spark/read_file_carga_hive.py','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ftp_puerto','9677','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ftp_user','NABIFI01','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ftp_hostname','10.112.47.36','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ftp_pass','bii2022-NA10','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ftp_path','/Distribuidores.csv','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','cola_ejecucion','capa_semantica','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ruta','/RGenerator/reportes/VENTAS_HUNTER','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_ARCHIVO','Distribuidores.csv','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','ftp_path_envio','/','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE1','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE1','carga_distribuidores','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_POST_FIJO',' ','94','1');

#  ----- SQOOP_IMPORT_TRX_5D.sh
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_SHELL2','SQOOP_IMPORT_TRX_5D.sh','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_PYTHON2','otc_v_sim_trx_5d_tem.py','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDUSER','NAPM_SCL01REP','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDPASS','kesmeri_09','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDHOST','10.112.146.18','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_FECHA_REPORTE','20221202','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE2','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE2','OTC_V_SIM_TRX_5D_TEM','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE3','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE3','OTC_V_SIM_TRX_5D','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBORACLE','nasptgen','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLORACLE','otc_v_sim_trx_5d','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TIPO_CARGA','overwrite','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_MASTER','yarn','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_DRIVER_MEMORY','16G','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_EXECUTOR_MEMORY','32G','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_NUM_EXECUTORS','3','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_CORE_EXECUTORS','4','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_COLUMNA_PARTICION','c_sim_trans_date','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_NUMERO_DIAS','5','94','1');



#  ----- sqoop_import_ventas_hunter
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_SHELL3','sqoop_import_ventas_hunter.sh','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_PYTHON3','import_ventas_hunter.py','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE4','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE4','otc_v_partner_sim','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE5','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE5','otc_v_settrans_pm_pkt','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBORACLE1','nasptgen','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLORACLE1','otc_v_partner_sim','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBORACLE2','nasptgen','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLORACLE2','otc_v_settrans_pm_pkt','94','1');

#------------inventario_ventas.sh
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_SHELL4','inventario_ventas.sh','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_PYTHON4','inventario_ventas.py','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE6','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE6','t_geographical_locations_TMP','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE7','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE7','OTC_V_SIM_TRX_5D_TEM2','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE8','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE8','OTC_V_SIM_TRX_5D_TEM3','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE9','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE9','otc_t_Ventas_Hunter_TMP','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE10','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE10','otc_t_Inventario_Hunter_TMP','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE11','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE11','otc_t_conteo_ventas','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE12','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE12','otc_t_conteo_ventas_dia','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE13','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE13','otc_t_Ventas_hunter_acumuladas','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TDBHIVE14','db_temporales','94','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('VENTAS_HUNTER','VAL_TTBLHIVE14','otc_t_Ventas_hunter_acumuladas_reporte','94','1');



