----


DELETE FROM params where ENTIDAD='BIGCSALTBAJINV0391';
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','RUTA','/RGenerator/cp_altas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','HIVEDB','db_cs_altas','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','VAL_MASTER','yarn','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','VAL_DRIVER_MEMORY','2G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','VAL_EXECUTOR_MEMORY','4G','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','VAL_NUM_EXECUTORS','10','0','1');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIGCSALTBAJINV0391','VAL_EXECUTOR_CORES','4','0','1');






-----
drop table db_cs_altas.otc_t_bajas_involuntarias;
CREATE TABLE db_cs_altas.otc_t_bajas_involuntarias(
  num_telefonico varchar(20), 
  fecha_proceso date, 
  fecha_ejecucion varchar(20), 
  marca string)
PARTITIONED BY ( 
  proces_date int)
CLUSTERED BY ( 
  fecha_proceso) 
INTO 3 BUCKETS
STORED AS ORC TBLPROPERTIES ("transactional"="false",'ORC.COMPRESS' = 'SNAPPY');