DELETE FROM params WHERE entidad='BIOFRTSGRD0010';
DELETE FROM params WHERE entidad='BIOFRTSGRD0010_TEMP';

-- parametros shell original (primer comando)
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PARAM1_FECHA_EJEC','date_format(sysdate(),''%Y%m%d'')','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PARAM2_VAL_IMPUESTOS','12','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PARAM3_VAL_COLA_EJECUCION','capa_semantica','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PARAM4_VAL_CADENA_JDBC','jdbc:hive2://quisrvbigdata1.otecel.com.ec:2181,quisrvbigdata2.otecel.com.ec:2181,quisrvbigdata10.otecel.com.ec:2181,quisrvbigdata11.otecel.com.ec:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2?tez.queue.name=capa_semantica','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PARAM5_VAL_RUTA','/RGenerator/reportes/PRY_OFERTA_SUGERIDA','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PARAM6_VAL_USER','rgenerator','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','SHELL','/RGenerator/reportes/PRY_OFERTA_SUGERIDA/bin/OTC_T_OFERTA_SUGERIDA_PARQUE.sh','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','CORREOS_ADVERTENCIA','pablo.yepez@telefonica.com,maria.olivares@telefonica.com,natalia.trujillo@telefonica.com,daysi.quilumbasiavichay@telefonica.com','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','PERIODICIDAD','DIARIA','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','ETAPA','1','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDUSER ','APPMIMOVISTAR','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDHOST','gendb-scan','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDDB','trxdb','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDPASS','Movistar2017!','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDPORT','1521','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDTABLA','OTC_T_OFERTA_PERSONAL','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','TDTABLA_PREPAGO','OTC_T_OFERTA_PREPAGO','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_COUNTED_DAYS_INI','0','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_COUNTED_DAYS_87_FIN','87','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_COUNTED_DAYS_88_FIN','88','0','0');

-- parametros pyspark (segundo comando)
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','RUTA_PYTHON','/RGenerator/reportes/PRY_OFERTA_SUGERIDA/python','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_SQL_PYSPARK1','script_extrae_oferta_sugerida.py','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_SQL_PYSPARK2','otc_t_oferta_prepago.py','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_EXPORT_PYSPARK1','otc_t_oferta_personal_export.py','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_EXPORT_PYSPARK2','otc_t_oferta_prepago_export.py','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_NUM_EXECUTORS_CORES','4','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_MASTER','yarn','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_NUM_EXECUTORS','2','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_DRIVER_MEMORY','50G','0','0');
INSERT INTO params(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('BIOFRTSGRD0010','VAL_EXECUTOR_MEMORY','50G','0','0');
